import os
import requests
from bs4 import BeautifulSoup


#==================================================================================================
# Archetypes with their corresponding classes
archetypes = {
    "Mage": ["Coercer", "Conjuror", "Illusionist", "Necromancer", "Warlock", "Wizard"],
    "Healer": ["Channeler", "Defiler", "Fury", "Inquisitor", "Mystic", "Templar", "Warden"],
    "Scout": ["Assassin", "Beastlord", "Brigand", "Dirge", "Ranger", "Swashbuckler", "Troubador"],
    "Fighter": ["Berserker", "Bruiser", "Guardian", "Monk", "Paladin", "Shadowknight"]
}
#==================================================================================================

def scrape_spells(class_name):
    url = f"https://u.eq2wire.com/spells/list_spells/{class_name}"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    filtered_spells = []
    for row in soup.find_all('tr', class_=['td-alt0', 'td-alt1']):
        cells = row.find_all('td')
        if cells and len(cells) >= 2:
            level_cell = cells[0].get_text().strip()
            if level_cell.isdigit():
                level = int(level_cell)
                if 126 <= level <= 130:
                    spell_name_tag = row.find('div', class_='spell_name').find('a')
                    if spell_name_tag:  # Check if the tag is not None
                        spell_name = spell_name_tag.get_text()
                        filtered_spells.append(spell_name)

    return filtered_spells

#==================================================================================================
# Get Desktop path for any user
desktop = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')

# Create folders for each archetype on the desktop and save the files
for archetype, classes in archetypes.items():
    archetype_folder = os.path.join(desktop, archetype)
    os.makedirs(archetype_folder, exist_ok=True)
#==================================================================================================

    for class_name in classes:
        spells = scrape_spells(class_name)
        xml_content = "<?xml version='1.0' encoding='UTF-8'?>\n"
        xml_content += "<!-- Generated by LavishSettings v2 -->\n"
        xml_content += "<InnerSpaceSettings>\n"
        for spell in spells:
            xml_content += f'<Setting Name="{spell} (Expert)">1</Setting>\n'
        xml_content += "</InnerSpaceSettings>\n"

        file_path = os.path.join(archetype_folder, f'{class_name}_126-130.xml')
        with open(file_path, 'w') as file:
            file.write(xml_content)

        print(f"{class_name} spells saved to {file_path}")
