import os
import re
import requests
from bs4 import BeautifulSoup

# Archetypes with their corresponding classes
archetypes = {
    "Mage": ["Coercer", "Conjuror", "Illusionist", "Necromancer", "Warlock", "Wizard"],
    "Healer": ["Channeler", "Defiler", "Fury", "Inquisitor", "Mystic", "Templar", "Warden"],
    "Scout": ["Assassin", "Beastlord", "Brigand", "Dirge", "Ranger", "Swashbuckler", "Troubador"],
    "Fighter": ["Berserker", "Bruiser", "Guardian", "Monk", "Paladin", "Shadowknight"]
}

ids = [
    "Spells_by_Tier_and_Level",
    "Combat_Arts_by_Tier_and_Level",
    "Spells_and_Combat_Arts_by_Tier_and_Level",
]
tier_re = re.compile(r"Tier\s*(\d+)")


def scrape_spells(class_name):
    url = f"https://eq2classic.fandom.com/wiki/Category:{class_name}"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    heading = None
    for id_ in ids:
        heading = soup.find(id=id_)
        if heading:
            break
    if not heading:
        print(f"No tier table found for {class_name}")
        return {}

    table = heading.find_next("table")
    tiers = {}
    headers = []

    for row in table.find_all("tr"):
        ths = row.find_all("th")
        if ths:
            headers = [th.get_text(" ", strip=True) for th in ths]
            continue

        tds = row.find_all("td")
        if headers and tds:
            for h, td in zip(headers, tds):
                m = tier_re.search(h)
                if not m:
                    continue
                tier = m.group(1)
                spells = [
                    b.find_next(["a", "span"]).get_text(strip=True)
                    for b in td.find_all("b")
                    if b.find_next(["a", "span"])
                ]
                tiers[tier] = spells
            headers = []

    return tiers

# Set the target directory , change if needed
target_directory = r"C:\Program Files (x86)\InnerSpace\Scripts\EQ2OgreCraft\RecipeQueues"
os.makedirs(target_directory, exist_ok=True)

# Scrape spells and save the files
def main():
    for archetype, classes in archetypes.items():
        for class_name in classes:
            tiers = scrape_spells(class_name)
            for tier_num in range(1, 9):
                spells = tiers.get(str(tier_num), [])
                xml_content = "<?xml version='1.0' encoding='UTF-8'?>\n"
                xml_content += "<!-- Generated by LavishSettings v2 -->\n"
                xml_content += "<InnerSpaceSettings>\n"
                for spell in spells:
                    xml_content += f'<Setting Name="{spell} (Adept III)">1</Setting>\n'
                xml_content += "</InnerSpaceSettings>\n"

                file_path = os.path.join(target_directory, f'{class_name}_Tier{tier_num}.xml')
                with open(file_path, 'w') as file:
                    file.write(xml_content)

                print(f"{class_name} Tier {tier_num} spells saved to {file_path}")


if __name__ == "__main__":
    main()
